# This file was generated by GoReleaser. DO NOT EDIT.
class Ecctl < Formula
  desc "Elastic Cloud Control, the official Elastic Cloud and ECE command line interface"
  homepage "https://github.com/elastic/ecctl"
  version "1.0.0-beta1"

  if OS.mac?
    url "https://github.com/elastic/ecctl/releases/download/v1.0.0-beta1/ecctl_v1.0.0-beta1_darwin_amd64.tar.gz"
    sha256 "2dd108520121dc9937ebc5bd61d730dd92207f797c6257fbb33a3bed1d7a83c3"
  elsif OS.linux?
    url "https://github.com/elastic/ecctl/releases/download/v1.0.0-beta1/ecctl_v1.0.0-beta1_linux_amd64.tar.gz"
    sha256 "36a9e358b8da64c19da25ff7a032ad32599dfa462ddf627f9b6cb51b5d607f09"
  end

  def install
    bin.install "ecctl"
    system "#{bin}/ecctl", "generate", "completions", "-l", "#{var}/ecctl.auto"
  end

  def caveats; <<~EOS
    If you have previously built ecctl from source, make sure you've removed that binary from any directory that has been added to your user $PATH.
    To enable autocompletion make sure to run `source <(ecctl generate completions)` and add it to your shell interpreter configuration file by running `echo "source <(ecctl generate completions)" >> ~/.bash_profile` or `echo "source <(ecctl generate completions)" >> ~/.zshrc` in case you are using ZSH.
  EOS
  end

  test do
    system "#{bin}/ecctl version"
  end
end
