# This file was generated by GoReleaser. DO NOT EDIT.
class Ecctl < Formula
  desc "Elastic Cloud Control, the official Elastic Cloud and ECE command line interface"
  homepage "https://github.com/elastic/ecctl"
  version "1.0.0-rc1"

  if OS.mac?
    url "https://github.com/elastic/ecctl/releases/download/1.0.0-rc1/ecctl_1.0.0-rc1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "ba8ba035995100f396d5e6de017909a782edf60ef3a1a0783b14976ad1c582c0"
  elsif OS.linux?
    url "https://github.com/elastic/ecctl/releases/download/1.0.0-rc1/ecctl_1.0.0-rc1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "4654d78ec273ef7aa2d5f790621a588974d889fe68c5b1f5a7370ce2937df319"
  end

  def install
    bin.install "ecctl"
    system "#{bin}/ecctl", "generate", "completions", "-l", "#{var}/ecctl.auto"
  end

  def caveats; <<~EOS
    Make sure to source #{var}/ecctl.auto for autocompletions
    If you have previously built ecctl from source, make sure you've removed that 
    binary from any directory that has been added to your user $PATH.
  EOS
  end

  test do
    system "#{bin}/ecctl version"
  end
end
